# Generated by Django 4.2.16 on 2024-09-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderonline',
            name='user_phone',
            field=models.CharField(max_length=14, verbose_name='Контактный телефон заказчика'),
        ),
        migrations.AlterField(
            model_name='orderphone',
            name='user_phone',
            field=models.CharField(max_length=14, verbose_name='Контактный телефон заказчика'),
        ),
    ]
